<?php
return [
    'users' => [
        'ADMIN'   => 'Admin',
        'TEACHER' => 'Teacher',
        'STUDENT' => 'Student',
    ],
    'form'  => [
        'FORM ONE'   => 'Form One',
        'FORM TWO'   => 'Form Two',
        'FORM THREE' => 'Form Three',
        'FORM FOUR'  => 'Form Four',
    ],

    'subjects' => [
        'MATHEMATICS' => 'Mathematics',
        'ENGLISH'     => 'English',
        'KISWAHILI'   => 'Kiswahili',
        'BIOLOGY'     => 'Biology',
        'PHYSICS'     => 'Physics',
        'CHEMISTRY'   => 'Chemistry',
        'GEOGRAPHY'   => 'Geography',
        'AGRICULTURE' => 'Agriculture',
        'BUSINESS'    => 'Business',
    ],
        'topic' => [
            'MATHEMATICS' => [
                'Natural Numbers '                         => 'Natural Numbers',
                'Factors'                                  => 'Factors',
                'Divisibility Tests'                       => 'Divisibility Tests',
                'Greatest Common Divisor(GCD)'             => 'Greatest Common Divisor(GCD)',
                'Least Common Multiple(L . C . M)'         => 'Least Common Multiple(L . C . M)',
                'Integers'                                 => 'Integers',
                'Fractions'                                => 'Fractions',
                'Decimals'                                 => 'Decimals',
                'Squares and Square Roots'                 => 'Squares and Square Roots',
                'Algebraic Expressions'                    => 'Algebraic Expressions',
                'Rates, Ratio, Percentages and Proportion' => 'Rates, Ratio, Percentages and Proportion',
                'Length'                                   => 'Length',
                'Area'                                     => 'Area',
                'Volume and Capacity'                      => 'Volume and Capacity',
                'Mass, Density and Weight'                 => 'Mass, Density and Weight',
                'Time'                                     => 'Time',
                'Linear Equations'                         => 'Linear Equations',
                'Commercial Arithmetic'                    => 'Commercial Arithmetic',
                'Co-ordinates and Graphs'                  => 'Co-ordinates and Graphs',
                'Angles and Plane Figures'                 => 'Angles and Plane Figures',
                'Geometric Constructions'                  => 'Geometric Constructions',
                'Scale Drawing'                            => 'Scale Drawing',
                'Common Solids'                            => 'Common Solids',

            ],
            'ENGLISH'     => [
                'Introduction to Biology'         => 'Introduction to Biology',
                'Classification I'                => 'Classification I',
                'The Cell'                        => 'The Cell',
                'Cell Physiology'                 => 'Cell Physiology',
                'Nutrition in Plants and Animals' => 'Nutrition in Plants and Animals',

            ],
        ],


    'FORM TWO' => [


    ],

    'counties' => [

        'MOMBASA'         => 'Mombasa',
        'KWALE'           => 'Kwale',
        'KILIFI'          => 'Kilifi',
        'TANA-RIVER'      => 'Tana River',
        'LAMU'            => 'Lamu',
        'TAITA'           => 'Taita–Taveta',
        'GARISSA'         => 'Garissa',
        'WAJIR'           => 'Wajir',
        'MANDERA'         => 'Mandera',
        '1MARSABIT'       => 'Marsabit',
        'ISIOLO'          => 'Isiolo',
        'MERU'            => 'Meru',
        'THARAKA-NITHI'   => 'Tharaka-Nithi',
        'EMBU'            => 'Embu',
        'KITUI'           => 'Kitui',
        'MACHAKOS'        => 'Machakos',
        'MAKUENI'         => 'Makueni',
        'NYANDARUA'       => 'Nyandarua',
        'NYERI'           => 'Nyeri',
        'KIRINYAGA'       => 'Kirinyaga',
        'MURANGA'         => 'Muranga',
        'KIAMBU'          => 'Kiambu',
        'TURKANA'         => 'Turkana',
        'POKOT'           => 'West Pokot',
        'SAMBURU'         => 'Samburu',
        'TRANS-NZOIA'     => 'Trans-Nzoia',
        'UASIN GISHU'     => 'Uasin Gishu',
        'ELGEYO-MARAKWET' => 'Elgeyo-Marakwet',
        'NANDI'           => 'Nandi',
        'BARINGO'         => 'Baringo',
        'LAIKIPIA'        => 'Laikipia',
        'NAKURU'          => 'Nakuru',
        'NAROK'           => 'Narok',
        'KAJIADO'         => 'Kajiado',
        'KERICHO'         => 'Kericho',
        'BOMET'           => 'Bomet',
        'KAKAMEGA'        => 'Kakamega',
        'VIHIA'           => 'Vihiga',
        'BUNGOMA'         => 'Bungoma',
        'BUSIA'           => 'Busia',
        'SIAYA'           => 'Siaya',
        'KISUMU'          => 'Kisumu',
        'HOMA BAY'        => 'Homa Bay',
        'MIGORI'          => 'Migori',
        'KISII'           => 'Kisii',
        'MYAMIRA'         => 'Nyamira',
        'NAIROBI'         => 'Nairobi',
    ],
];