<?php
return [
    'users' => [
        'ADMIN'   => 'Admin',
        'TEACHER' => 'Teacher',
        'STUDENT' => 'Student',
    ],
    'form'  => [
        'FORM ONE'   => 'form one',
        'FORM TWO'   => 'form two',
        'FORM THREE' => 'form three',
        'FORM FOUR'  => 'form four',
    ],

    'subjects' => [
        'MATHEMATICS' => 'Mathematics',
        'ENGLISH'     => 'English',
        'KISWAHILI'   => 'Kiswahili',
        'BIOLOGY'     => 'Biology',
        'PHYSICS'     => 'Physics',
        'CHEMISTRY'   => 'Chemistry',
        'GEOGRAPHY'   => 'Geography',
        'AGRICULTURE' => 'Agriculture',
        'BUSINESS'    => 'Business',
    ],

    'counties' => [

        'MOMBASA'         => 'Mombasa',
        'KWALE'           => 'Kwale',
        'KILIFI'          => 'Kilifi',
        'TANA-RIVER'      => 'Tana River',
        'LAMU'            => 'Lamu',
        'TAITA'           => 'Taita–Taveta',
        'GARISSA'         => 'Garissa',
        'WAJIR'           => 'Wajir',
        'MANDERA'         => 'Mandera',
        '1MARSABIT'       => 'Marsabit',
        'ISIOLO'          => 'Isiolo',
        'MERU'            => 'Meru',
        'THARAKA-NITHI'   => 'Tharaka-Nithi',
        'EMBU'            => 'Embu',
        'KITUI'           => 'Kitui',
        'MACHAKOS'        => 'Machakos',
        'MAKUENI'         => 'Makueni',
        'NYANDARUA'       => 'Nyandarua',
        'NYERI'           => 'Nyeri',
        'KIRINYAGA'       => 'Kirinyaga',
        'MURANGA'         => 'Muranga',
        'KIAMBU'          => 'Kiambu',
        'TURKANA'         => 'Turkana',
        'POKOT'           => 'West Pokot',
        'SAMBURU'         => 'Samburu',
        'TRANS-NZOIA'     => 'Trans-Nzoia',
        'UASIN GISHU'     => 'Uasin Gishu',
        'ELGEYO-MARAKWET' => 'Elgeyo-Marakwet',
        'NANDI'           => 'Nandi',
        'BARINGO'         => 'Baringo',
        'LAIKIPIA'        => 'Laikipia',
        'NAKURU'          => 'Nakuru',
        'NAROK'           => 'Narok',
        'KAJIADO'         => 'Kajiado',
        'KERICHO'         => 'Kericho',
        'BOMET'           => 'Bomet',
        'KAKAMEGA'        => 'Kakamega',
        'VIHIA'           => 'Vihiga',
        'BUNGOMA'         => 'Bungoma',
        'BUSIA'           => 'Busia',
        'SIAYA'           => 'Siaya',
        'KISUMU'          => 'Kisumu',
        'HOMA BAY'        => 'Homa Bay',
        'MIGORI'          => 'Migori',
        'KISII'           => 'Kisii',
        'MYAMIRA'         => 'Nyamira',
        'NAIROBI'         => 'Nairobi',
    ],
];